---
title: Happiness around the world in the face of covid
author: by MZM
output: github_document
---

## Summary

Introduction

We are examining the following question: What makes a country 'happy'?
We define happiness in terms of our well-being and the well-being of the planet, as both factors are essential to create long lasting happiness.
To answer our question we look at the Happy Planet Index dataset, which collects data about countries around the world and compares them by calculating their happy planet index (hpi), which is a combined measure of life expectancy, reported happiness and ecological footprint of a country. 
We also aim to consider the impact of the covid pandemic on countries' hpi scores.

We have decided to examine our data under three categories which we believe affect hpi scores of countries, these categories being - *Economic*, *Wellbeing*, and *Ecological*.

Economic Analysis

Countries with highest hpi have neither very high nor very low gdp per capita.
Moreover when gdp per capita is plotted against happy life years (a measure which combines life expectancy and well-being to assess life quality) we see that the relationship is logarithmic, therefore if our aim is to try to increase global happiness we should invest money in the poorest nations as this would bring about the biggest change. Also mention the dangerous of splitting up data and fitting separate linear models over these groupings - a way to introduce error in analysis that should be addressed but we weren't taught how to in the course.

Ecological Analysis

From 2016 to 2019 most countries have an increasing or steady ecological footprint but from
2019 to 2020 we see a decline from virtually every nation observed. 
This is not only a trend followed by similar countries as the gdp of countries in
these regions vary significantly with africa being a lot lower than the rest. There are 
many possible reasons for this change but most obvious would be covid.
The large scale closures and lockdowns would have led to less resources being required
thus lowering countries ecological footprint. Other reasons could be governments being
more proactive about climate change but this would not explain how wide spread this
decrease is.

We can also observe that in general the higher a nations gdp the higher the eco footprint but
looking at east asia and europe tells a different story where there seems to be no link or
the opposite of what is expected. This is to be expected from a data set like this since 
countries and regions vary wildly due to culture, politics, beliefs and much more.

Conclusion

In conclusion we can see that there are many different factors that can affect the happiness,
wealth and eco-friendliness of a nation and each of these are also affected by outside forces
such as a pandemic or more awareness of problems. It is also clear that countries need many
positive characteristics to rank highly on the HPI and contribute to a happier world. When
comparing many regions and even countries it is always important to keep in mind trends and
other anomalies that are created due to possibly political or cultural diversity between
these regions and other factors. What we have managed to show is that there are clear trends
in the data but also anomalies but ultimately we have shown what is required to create a 
happy planet and trends that are associated with it.

## Presentation

Our presentation can be found [here](presentation/CopyOfXaringan_template/presentation.html).

## Data 

Include a citation for your data here. 
See http://libraryguides.vu.edu.au/c.php?g=386501&p=4347840 for guidance on proper citation for datasets. 
If you got your data off the web, make sure to note the retrieval date.

## References

List any references here. You should, at a minimum, list your data source.

